--------------------------------------------------------
-- Archivo creado  - martes-marzo-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body PKG_REQUERIMIENTOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "EVA"."PKG_REQUERIMIENTOS" AS

  PROCEDURE SP_BUSCAR_REQUERIMIENTO(
                              P_FONDO_ID            IN COB_REQ_CARTAS.FONDO_ID%TYPE,     
                              P_DVALOR_BV           IN COB_REQ_CARTAS.DVALOR_BV%TYPE,                               
                              P_CUOTA_DIA1          IN COB_REQ_CRITERIOS.CUOTA_DIA%TYPE,
                              P_CUOTA_DIA2          IN COB_REQ_CRITERIOS.CUOTA_DIA%TYPE,
                              P_REQ_ENVIO1          IN COB_REQ_CARTAS.REQ_ENVIO%TYPE,
                              P_REQ_ENVIO2          IN COB_REQ_CARTAS.REQ_ENVIO%TYPE,
                              P_REQ_RECEPCION1      IN COB_REQ_CARTAS.REQ_RECEPCION%TYPE,
                              P_REQ_RECEPCION2      IN COB_REQ_CARTAS.REQ_RECEPCION%TYPE,
                              P_TNOMBRES            IN SACIF.PERSONA.TNOMBRES%TYPE,
                              P_REQ_ESTADO          IN COB_REQ_CARTAS.REQ_ESTADO%TYPE, 
                              P_TIPO_CARTA          IN COB_REQ_CARTAS.TIPO_CARTA%TYPE,
                              P_PRIORI              IN COB_TABLAS.PRIORI%TYPE,
                              P_RESULTADO           OUT cursorType) AS
  BEGIN
  OPEN P_RESULTADO FOR
  SELECT 
    T1.REQ_TIPO,
	T1.REQ_NUMERO,
	T5.C_MAE_INVERSION_ID,
	T5.C_INVERSION_ID,
	T1.FONDO_ID,
    T3.D_ABREVIADO,
	T1.DVALOR_BV,
	T1.REQ_EMISION,
	T1.TIPO_CARTA,
    T2.D_DESCRIPCION DESC_CARTA,
	T1.REQ_ESTADO,
	T1.REQ_COMENTARIO,
	T1.C_USUARIO_ADD,
	T1.F_USUARIO_ADD,
	T1.C_USUARIO_MOD,
	T1.F_USUARIO_MOD,
	T1.REQ_ENVIO,
	T1.REQ_RECEPCION,
    T4.TAPATERNO, 
    T4.TAMATERNO, 
    T4.TNOMBRES,
    T4.DUBIGEO,
    T4.CUOTAS

  FROM COB_REQ_CARTAS T1
  INNER JOIN COB_TABLAS T2 ON T1.TIPO_CARTA=T2.C_TABLA_DET_ID AND T2.C_TABLA_ID='0622'
  INNER JOIN MAE_FONDO T3 ON T1.FONDO_ID=T3.C_FONDO_ID
  INNER JOIN (    

        SELECT '0001' C_FONDO_ID, I5.NINVERSION, I1.DVALOR_BV, I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I4.DUBIGEO, TRUNC((I8.MSALDO*-1)/DECODE(I6.MCUOTA,0,1,I6.MCUOTA)) CUOTAS
        FROM SACIF.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF.INMUEBLE I3 ON I1.CINMUEBLE=I3.CINMUEBLE
        INNER JOIN SACIF.UBIGEO I4 ON I3.CUBIGEO=I4.CUBIGEO
        INNER JOIN SACIF.MAESTRO_INVERSION I5 ON I1.DVALOR_BV=I5.DVALOR_BV
        INNER JOIN SACIF.CRONOGRAMA_PAGO I6 ON I5.NINVERSION=I6.NINVERSION AND I6.NCUOTA=1
        INNER JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF.ESTADO_CUENTA_TCHN
        GROUP BY NINVERSION) I7 ON I5.NINVERSION=I7.NINVERSION
        INNER JOIN SACIF.ESTADO_CUENTA_TCHN I8 ON I7.NINVERSION=I8.NINVERSION AND I7.NSECUENCIA=I8.NSECUENCIA             



        UNION ALL

        SELECT '0002' C_FONDO_ID,  I5.NINVERSION, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I4.DUBIGEO, TRUNC((I8.MSALDO*-1)/DECODE(I6.MCUOTA,0,1,I6.MCUOTA)) CUOTAS
        FROM SACIF_POP.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_POP.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF_POP.INMUEBLE I3 ON I1.CINMUEBLE=I3.CINMUEBLE
        INNER JOIN SACIF_POP.UBIGEO I4 ON I3.CUBIGEO=I4.CUBIGEO       
        INNER JOIN SACIF_POP.MAESTRO_INVERSION I5 ON I1.DVALOR_BV=I5.DVALOR_BV
        INNER JOIN SACIF_POP.CRONOGRAMA_PAGO I6 ON I5.NINVERSION=I6.NINVERSION AND I6.NCUOTA=1
        INNER JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF_POP.ESTADO_CUENTA_TCHN
        GROUP BY NINVERSION) I7 ON I5.NINVERSION=I7.NINVERSION
        INNER JOIN SACIF_POP.ESTADO_CUENTA_TCHN I8 ON I7.NINVERSION=I8.NINVERSION AND I7.NSECUENCIA=I8.NSECUENCIA  


        UNION ALL

        SELECT '0003' C_FONDO_ID,  I5.NINVERSION, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I4.DUBIGEO, TRUNC((I8.MSALDO*-1)/DECODE(I6.MCUOTA,0,1,I6.MCUOTA)) CUOTAS
        FROM SACIF_MYP.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_MYP.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF_MYP.INMUEBLE I3 ON I1.CINMUEBLE=I3.CINMUEBLE
        INNER JOIN SACIF_MYP.UBIGEO I4 ON I3.CUBIGEO=I4.CUBIGEO  
        INNER JOIN SACIF_MYP.MAESTRO_INVERSION I5 ON I1.DVALOR_BV=I5.DVALOR_BV
        INNER JOIN SACIF_MYP.CRONOGRAMA_PAGO I6 ON I5.NINVERSION=I6.NINVERSION AND I6.NCUOTA=1
        INNER JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF_MYP.ESTADO_CUENTA_TCHN
        GROUP BY NINVERSION) I7 ON I5.NINVERSION=I7.NINVERSION
        INNER JOIN SACIF_MYP.ESTADO_CUENTA_TCHN I8 ON I7.NINVERSION=I8.NINVERSION AND I7.NSECUENCIA=I8.NSECUENCIA   


        UNION ALL

        SELECT '0004' C_FONDO_ID, I5.NINVERSION, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I4.DUBIGEO, TRUNC((I8.MSALDO*-1)/DECODE(I6.MCUOTA,0,1,I6.MCUOTA)) CUOTAS
        FROM SACIF_PRH.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_PRH.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA 
        INNER JOIN SACIF_PRH.INMUEBLE I3 ON I1.CINMUEBLE=I3.CINMUEBLE
        INNER JOIN SACIF_PRH.UBIGEO I4 ON I3.CUBIGEO=I4.CUBIGEO
        INNER JOIN SACIF_PRH.MAESTRO_INVERSION I5 ON I1.DVALOR_BV=I5.DVALOR_BV
        INNER JOIN SACIF_PRH.CRONOGRAMA_PAGO I6 ON I5.NINVERSION=I6.NINVERSION AND I6.NCUOTA=1
        INNER JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF_PRH.ESTADO_CUENTA_TCHN
        GROUP BY NINVERSION) I7 ON I5.NINVERSION=I7.NINVERSION
        INNER JOIN SACIF_PRH.ESTADO_CUENTA_TCHN I8 ON I7.NINVERSION=I8.NINVERSION AND I7.NSECUENCIA=I8.NSECUENCIA      


    ) T4 ON T4.C_FONDO_ID=T1.FONDO_ID AND TRIM(T4.DVALOR_BV)=TRIM(T1.DVALOR_BV)  
  INNER JOIN MAE_COD_INVERSION T5 ON T5.C_FONDO_ID=T1.FONDO_ID AND TRIM(T5.C_INVERSION)=TRIM(T1.DVALOR_BV) AND T5.C_INVERSION_ID=T4.NINVERSION
  INNER JOIN COB_TABLAS T6 ON T1.REQ_ESTADO=T6.C_TABLA_DET_ID AND T6.C_TABLA_ID='0623'
  INNER JOIN COB_REQ_CRITERIOS T7 ON T1.REQ_TIPO=T7.REQ_TIPO AND T1.REQ_NUMERO=T7.REQ_NUMERO

  WHERE 
    T1.IS_DELETE='N' AND
    T6.PRIORI > P_PRIORI AND
    T1.FONDO_ID LIKE '%'||P_FONDO_ID||'%' AND
    T1.DVALOR_BV LIKE '%'||P_DVALOR_BV||'%' AND
    T7.CUOTA_DIA >= NVL(P_CUOTA_DIA1,0) AND
    T7.CUOTA_DIA <= DECODE(NVL(P_CUOTA_DIA2,0),0,32,NVL(P_CUOTA_DIA2,0)) AND    
    (T1.REQ_ENVIO >= P_REQ_ENVIO1 OR P_REQ_ENVIO1 IS NULL) AND
    (T1.REQ_ENVIO <= P_REQ_ENVIO2 OR P_REQ_ENVIO2 IS NULL) AND
    (T1.REQ_RECEPCION >= P_REQ_RECEPCION1 OR P_REQ_RECEPCION1 IS NULL) AND
    (T1.REQ_RECEPCION <= P_REQ_RECEPCION2 OR P_REQ_RECEPCION2 IS NULL) AND
    T1.REQ_ESTADO LIKE '%'||P_REQ_ESTADO||'%' AND
    UPPER(T4.TAPATERNO||' '||T4.TAMATERNO||' '||T4.TNOMBRES) LIKE UPPER('%'||P_TNOMBRES||'%') AND
    T1.TIPO_CARTA LIKE '%'||P_TIPO_CARTA||'%'
    ORDER BY T1.REQ_NUMERO DESC, T1.TIPO_CARTA
  ;

  END SP_BUSCAR_REQUERIMIENTO;

  PROCEDURE SP_BUSCAR_REQ_CRITERIO(
                              P_REQ_TIPO           IN COB_REQ_CRITERIOS.REQ_TIPO%TYPE,
                              P_REQ_NUMERO         IN COB_REQ_CRITERIOS.REQ_NUMERO%TYPE,
                              P_RESULTADO     OUT cursorType) AS
  BEGIN

  OPEN P_RESULTADO FOR
      SELECT * FROM COB_REQ_CRITERIOS
      WHERE REQ_TIPO=P_REQ_TIPO AND REQ_NUMERO=P_REQ_NUMERO
      ORDER BY CRI_ITEM;

  END SP_BUSCAR_REQ_CRITERIO;

  PROCEDURE SP_REQ_SUGERIDOS(P_RESULTADO OUT cursorType) AS
  CURSOR C1 IS
    SELECT 
    '0001' CFOND,
    T1.NINVERSION,
    T1.DVALOR_BV,
    T1.FVCTO,
    T1.NPLAZO_MESES, 
    T1.NCUOTAS_GENERADAS,
    TO_NUMBER(TO_CHAR(T1.FVCTO,'DD')) CUOTA_DIA,    
    T2.MCUOTA, T4.MSALDO, TRUNC((T4.MSALDO*-1)/T2.MCUOTA) CUOTAS,
    T7.DOPERACION ULT_PAGO,
    TRUNC(SYSDATE)-T7.DOPERACION DIAS_SINPAGO,
    T8.NRO_2CUOTAS_ATRAS,
    NVL(T12.FRECUENCIA_PAGO,99) FRECUENCIA_PAGO,
    DECODE(TRIM(T10.S_TCHN),'00000',NULL,DECODE(TRIM(T10.S_TCHN),'000000',NULL,TRIM(T10.S_TCHN))) S_TCHN,
    T11.S_ASHIPO,

    T50.FEMISION CARTA_NOTARIAL_F1,
    T50.CANT_REI CARTA_NOTARIAL_R1,    
    (CASE WHEN TRUNC(SYSDATE) > T50.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O1,

    T54.FEMISION CARTA_NOTARIAL_F2,
    T54.CANT_REI CARTA_NOTARIAL_R2,  
    (CASE WHEN TRUNC(SYSDATE) > T54.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O2,

    T55.FEMISION CARTA_NOTARIAL_F3,
    T55.CANT_REI CARTA_NOTARIAL_R3, 
    (CASE WHEN TRUNC(SYSDATE) > T55.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O3,


    T90.FEMISION PROTESTO_NOTARIAL_F1,
    (CASE WHEN TRUNC(SYSDATE) > T90.FEMISION+15 THEN '*' ELSE NULL END) PROTESTO_NOTARIAL_O1,

    T52.FEMISION CARTA_PROTESTO_F1,
    T52.CANT_REI CARTA_PROTESTO_R1,
    (CASE WHEN TRUNC(SYSDATE) > T52.FEMISION+15 THEN '*' ELSE NULL END) CARTA_PROTESTO_O1,

    T53.FEMISION CARTA_PREJECUCION_F1,
    T53.CANT_REI CARTA_PREJECUCION_R1,
    (CASE WHEN TRUNC(SYSDATE) > T53.FEMISION+15 THEN '*' ELSE NULL END) CARTA_PREJECUCION_O1

    FROM SACIF.MAESTRO_INVERSION T1
    INNER JOIN SACIF.CRONOGRAMA_PAGO T2 ON T1.NINVERSION=T2.NINVERSION AND T2.NCUOTA=1
    INNER JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF.ESTADO_CUENTA_TCHN 
    GROUP BY NINVERSION) T3 ON T1.NINVERSION=T3.NINVERSION
    INNER JOIN SACIF.ESTADO_CUENTA_TCHN T4 ON T1.NINVERSION=T4.NINVERSION AND T3.NINVERSION=T4.NINVERSION AND T3.NSECUENCIA=T4.NSECUENCIA

    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0002','0001',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0002','0001',TIPOCARTA)) T50 ON T50.TIPOCARTA IN('0001','0002') AND TRIM(T50.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0009','0007',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0009','0007',TIPOCARTA)) T54 ON T54.TIPOCARTA IN('0007','0009') AND TRIM(T54.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0010','0008',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0010','0008',TIPOCARTA)) T55 ON T55.TIPOCARTA IN('0008','0010') AND TRIM(T55.DVALOR_BV)=TRIM(T1.DVALOR_BV)


    LEFT JOIN (SELECT DVALOR_BV, TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, TIPOCARTA) T52 ON T52.TIPOCARTA='0003' AND TRIM(T52.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, TIPOCARTA) T53 ON T53.TIPOCARTA='0004' AND TRIM(T53.DVALOR_BV)=TRIM(T1.DVALOR_BV)

    LEFT JOIN CTDIA.MOVIMIENTO_PROTESTO T90 ON  T90.DOC_TIPO='PN' AND  TRIM(T90.DVALOR_BV)=TRIM(T1.DVALOR_BV)

    LEFT JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF.ESTADO_CUENTA_TCHN WHERE MABONO<>0
    GROUP BY NINVERSION) T6 ON T1.NINVERSION=T6.NINVERSION
    LEFT JOIN SACIF.ESTADO_CUENTA_TCHN T7 ON T1.NINVERSION=T7.NINVERSION AND T6.NSECUENCIA=T7.NSECUENCIA

    LEFT JOIN (
    SELECT 
    T1.CFOND,
    T1.NINVERSION,
    COUNT(T3.MCARGO) NRO_2CUOTAS_ATRAS
    FROM SACIF.MAESTRO_INVERSION T1
    INNER JOIN SACIF.CRONOGRAMA_PAGO T2 ON T1.NINVERSION=T2.NINVERSION AND T2.NCUOTA=1
    INNER JOIN SACIF.ESTADO_CUENTA_TCHN T3 ON T1.NINVERSION=T3.NINVERSION AND T3.CCONCEPTO='0001' AND T3.DOPERACION>=(SYSDATE-10080)
    WHERE NVL(T1.FCANCELADO,'N')='N'  AND NVL(T1.FJUDICIAL,'N')='N'
    AND TRUNC(T3.MSALDO*-1) >= TRUNC(T2.MCUOTA*2)
    AND TRUNC(T3.MSALDO*-1) < TRUNC(T2.MCUOTA*3)
    GROUP BY T1.CFOND, T1.NINVERSION
    ) T8 ON T1.CFOND=T8.CFOND AND T1.NINVERSION=T8.NINVERSION

    LEFT JOIN (
    SELECT DVALOR_BV, S_TCHN
    FROM CTDIA.MAE_CUSTODIA WHERE C_FONDO_ID='0001' AND DOCUMENTO_ID='0015'
    ) T10 ON TRIM(T1.DVALOR_BV)=TRIM(T10.DVALOR_BV)
    LEFT JOIN (
    SELECT  DVALOR_BV,S_ASHIPO,S_PEHIPO,S_ASEXPTCHN
    FROM CTDIA.MAE_CUSTODIA WHERE C_FONDO_ID='0001' AND DOCUMENTO_ID='0014'
    ) T11 ON  TRIM(T1.DVALOR_BV)=TRIM(T11.DVALOR_BV)

    LEFT JOIN (
        SELECT NINVERSION, ROUND(AVG(DIAS)) FRECUENCIA_PAGO  FROM
        (
            SELECT 
            Q1.NINVERSION,
            Q1.NSECUENCIA,
            Q1.MABONO,
            Q1.MCARGO,
            Q1.MSALDO,
            MAX(Q2.DOPERACION) DOPERACION_ANTE,
            Q1.DOPERACION,
            Q1.DOPERACION-MAX(Q2.DOPERACION) DIAS
            FROM SACIF.ESTADO_CUENTA_TCHN Q1 
            INNER JOIN SACIF.ESTADO_CUENTA_TCHN Q2 ON Q1.NINVERSION=Q2.NINVERSION AND Q1.NSECUENCIA>Q2.NSECUENCIA AND Q2.CCONCEPTO='0002'
            WHERE  Q1.CCONCEPTO='0002'
            GROUP BY Q1.NINVERSION,
            Q1.NSECUENCIA,
            Q1.DOPERACION,
            Q1.MABONO,
            Q1.MCARGO,
            Q1.MSALDO
            HAVING Q1.DOPERACION-MAX(Q2.DOPERACION)>15
            ORDER BY Q1.NSECUENCIA
        ) GROUP BY NINVERSION
    ) T12 ON  T1.NINVERSION=T12.NINVERSION

    WHERE NVL(T1.FCANCELADO,'N')='N' AND NVL(T1.FJUDICIAL,'N')='N' AND NVL(T1.EXTRAJUDICIAL,'N')='N'

    UNION ALL

    SELECT 
    '0002' CFOND,
    T1.NINVERSION,
    T1.DVALOR_BV,
    T1.FVCTO,
    T1.NPLAZO_MESES, 
    T1.NCUOTAS_GENERADAS,   
    TO_NUMBER(TO_CHAR(T1.FVCTO,'DD')) CUOTA_DIA,  
    T2.MCUOTA, T4.MSALDO, TRUNC((T4.MSALDO*-1)/T2.MCUOTA) CUOTAS,
    T7.DOPERACION ULT_PAGO,
    TRUNC(SYSDATE)-T7.DOPERACION DIAS_SINPAGO,
    T8.NRO_2CUOTAS_ATRAS,
    NVL(T12.FRECUENCIA_PAGO,99) FRECUENCIA_PAGO,
    DECODE(TRIM(T10.S_TCHN),'00000',NULL,DECODE(TRIM(T10.S_TCHN),'000000',NULL,TRIM(T10.S_TCHN))) S_TCHN,
    T11.S_ASHIPO,

    T50.FEMISION CARTA_NOTARIAL_F1,
    T50.CANT_REI CARTA_NOTARIAL_R1,    
    (CASE WHEN TRUNC(SYSDATE) > T50.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O1,

    T54.FEMISION CARTA_NOTARIAL_F2,
    T54.CANT_REI CARTA_NOTARIAL_R2,  
    (CASE WHEN TRUNC(SYSDATE) > T54.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O2,

    T55.FEMISION CARTA_NOTARIAL_F3,
    T55.CANT_REI CARTA_NOTARIAL_R3, 
    (CASE WHEN TRUNC(SYSDATE) > T55.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O3,


    T90.FEMISION PROTESTO_NOTARIAL_F1,
    (CASE WHEN TRUNC(SYSDATE) > T90.FEMISION+15 THEN '*' ELSE NULL END) PROTESTO_NOTARIAL_O1,

    T52.FEMISION CARTA_PROTESTO_F1,
    T52.CANT_REI CARTA_PROTESTO_R1,
    (CASE WHEN TRUNC(SYSDATE) > T52.FEMISION+15 THEN '*' ELSE NULL END) CARTA_PROTESTO_O1,

    T53.FEMISION CARTA_PREJECUCION_F1,
    T53.CANT_REI CARTA_PREJECUCION_R1,
    (CASE WHEN TRUNC(SYSDATE) > T53.FEMISION+15 THEN '*' ELSE NULL END) CARTA_PREJECUCION_O1

    FROM SACIF_POP.MAESTRO_INVERSION T1
    INNER JOIN SACIF_POP.CRONOGRAMA_PAGO T2 ON T1.NINVERSION=T2.NINVERSION AND T2.NCUOTA=1
    INNER JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF_POP.ESTADO_CUENTA_TCHN 
    GROUP BY NINVERSION) T3 ON T1.NINVERSION=T3.NINVERSION
    INNER JOIN SACIF_POP.ESTADO_CUENTA_TCHN T4 ON T1.NINVERSION=T4.NINVERSION AND T3.NINVERSION=T4.NINVERSION AND T3.NSECUENCIA=T4.NSECUENCIA

    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0002','0001',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0002','0001',TIPOCARTA)) T50 ON T50.TIPOCARTA IN('0001','0002') AND TRIM(T50.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0009','0007',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0009','0007',TIPOCARTA)) T54 ON T54.TIPOCARTA IN('0007','0009') AND TRIM(T54.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0010','0008',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0010','0008',TIPOCARTA)) T55 ON T55.TIPOCARTA IN('0008','0010') AND TRIM(T55.DVALOR_BV)=TRIM(T1.DVALOR_BV)


    LEFT JOIN (SELECT DVALOR_BV, TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, TIPOCARTA) T52 ON T52.TIPOCARTA='0003' AND TRIM(T52.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, TIPOCARTA) T53 ON T53.TIPOCARTA='0004' AND TRIM(T53.DVALOR_BV)=TRIM(T1.DVALOR_BV)

    LEFT JOIN CTDIA.MOVIMIENTO_PROTESTO T90 ON T90.DOC_TIPO='PN' AND TRIM(T90.DVALOR_BV)=TRIM(T1.DVALOR_BV)

    LEFT JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF_POP.ESTADO_CUENTA_TCHN WHERE MABONO<>0
    GROUP BY NINVERSION) T6 ON T1.NINVERSION=T6.NINVERSION
    LEFT JOIN SACIF_POP.ESTADO_CUENTA_TCHN T7 ON T1.NINVERSION=T7.NINVERSION AND T6.NSECUENCIA=T7.NSECUENCIA

    LEFT JOIN (
    SELECT 
    T1.CFOND,
    T1.NINVERSION,
    COUNT(T3.MCARGO) NRO_2CUOTAS_ATRAS
    FROM SACIF_POP.MAESTRO_INVERSION T1
    INNER JOIN SACIF_POP.CRONOGRAMA_PAGO T2 ON T1.NINVERSION=T2.NINVERSION AND T2.NCUOTA=1
    INNER JOIN SACIF_POP.ESTADO_CUENTA_TCHN T3 ON T1.NINVERSION=T3.NINVERSION AND T3.CCONCEPTO='0001' AND T3.DOPERACION>=(SYSDATE-10080)
    WHERE NVL(T1.FCANCELADO,'N')='N'  AND NVL(T1.FJUDICIAL,'N')='N'
    AND TRUNC(T3.MSALDO*-1) >= TRUNC(T2.MCUOTA*2)
    AND TRUNC(T3.MSALDO*-1) < TRUNC(T2.MCUOTA*3)
    GROUP BY T1.CFOND, T1.NINVERSION
    ) T8 ON T1.CFOND=T8.CFOND AND T1.NINVERSION=T8.NINVERSION

    LEFT JOIN (
    SELECT DVALOR_BV, S_TCHN
    FROM CTDIA.MAE_CUSTODIA WHERE C_FONDO_ID='0002' AND DOCUMENTO_ID='0015'
    ) T10 ON TRIM(T1.DVALOR_BV)=TRIM(T10.DVALOR_BV)
    LEFT JOIN (
    SELECT  DVALOR_BV,S_ASHIPO,S_PEHIPO,S_ASEXPTCHN
    FROM CTDIA.MAE_CUSTODIA WHERE C_FONDO_ID='0002' AND DOCUMENTO_ID='0014'
    ) T11 ON  TRIM(T1.DVALOR_BV)=TRIM(T11.DVALOR_BV)

    LEFT JOIN (
        SELECT NINVERSION, ROUND(AVG(DIAS)) FRECUENCIA_PAGO  FROM
        (
            SELECT 
            Q1.NINVERSION,
            Q1.NSECUENCIA,
            Q1.MABONO,
            Q1.MCARGO,
            Q1.MSALDO,
            MAX(Q2.DOPERACION) DOPERACION_ANTE,
            Q1.DOPERACION,
            Q1.DOPERACION-MAX(Q2.DOPERACION) DIAS
            FROM SACIF_POP.ESTADO_CUENTA_TCHN Q1 
            INNER JOIN SACIF_POP.ESTADO_CUENTA_TCHN Q2 ON Q1.NINVERSION=Q2.NINVERSION AND Q1.NSECUENCIA>Q2.NSECUENCIA AND Q2.CCONCEPTO='0002'
            WHERE  Q1.CCONCEPTO='0002'
            GROUP BY Q1.NINVERSION,
            Q1.NSECUENCIA,
            Q1.DOPERACION,
            Q1.MABONO,
            Q1.MCARGO,
            Q1.MSALDO
            HAVING Q1.DOPERACION-MAX(Q2.DOPERACION)>15
            ORDER BY Q1.NSECUENCIA
        ) GROUP BY NINVERSION
    ) T12 ON  T1.NINVERSION=T12.NINVERSION

    WHERE NVL(T1.FCANCELADO,'N')='N' AND NVL(T1.FJUDICIAL,'N')='N' AND NVL(T1.EXTRAJUDICIAL,'N')='N'

    UNION ALL

    SELECT 
    '0003' CFOND,
    T1.NINVERSION,
    T1.DVALOR_BV,
    T1.FVCTO,
    T1.NPLAZO_MESES, 
    T1.NCUOTAS_GENERADAS,    
    TO_NUMBER(TO_CHAR(T1.FVCTO,'DD')) CUOTA_DIA,  
    T2.MCUOTA, T4.MSALDO, TRUNC((T4.MSALDO*-1)/T2.MCUOTA) CUOTAS,
    T7.DOPERACION ULT_PAGO,
    TRUNC(SYSDATE)-T7.DOPERACION DIAS_SINPAGO,
    T8.NRO_2CUOTAS_ATRAS,
    NVL(T12.FRECUENCIA_PAGO,99) FRECUENCIA_PAGO,
    DECODE(TRIM(T10.S_TCHN),'00000',NULL,DECODE(TRIM(T10.S_TCHN),'000000',NULL,TRIM(T10.S_TCHN))) S_TCHN,
    T11.S_ASHIPO,

    T50.FEMISION CARTA_NOTARIAL_F1,
    T50.CANT_REI CARTA_NOTARIAL_R1,    
    (CASE WHEN TRUNC(SYSDATE) > T50.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O1,

    T54.FEMISION CARTA_NOTARIAL_F2,
    T54.CANT_REI CARTA_NOTARIAL_R2,  
    (CASE WHEN TRUNC(SYSDATE) > T54.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O2,

    T55.FEMISION CARTA_NOTARIAL_F3,
    T55.CANT_REI CARTA_NOTARIAL_R3, 
    (CASE WHEN TRUNC(SYSDATE) > T55.FEMISION+15 THEN '*' ELSE NULL END) CARTA_NOTARIAL_O3,


    T90.FEMISION PROTESTO_NOTARIAL_F1,
    (CASE WHEN TRUNC(SYSDATE) > T90.FEMISION+15 THEN '*' ELSE NULL END) PROTESTO_NOTARIAL_O1,

    T52.FEMISION CARTA_PROTESTO_F1,
    T52.CANT_REI CARTA_PROTESTO_R1,
    (CASE WHEN TRUNC(SYSDATE) > T52.FEMISION+15 THEN '*' ELSE NULL END) CARTA_PROTESTO_O1,

    T53.FEMISION CARTA_PREJECUCION_F1,
    T53.CANT_REI CARTA_PREJECUCION_R1,
    (CASE WHEN TRUNC(SYSDATE) > T53.FEMISION+15 THEN '*' ELSE NULL END) CARTA_PREJECUCION_O1

    FROM SACIF_MYP.MAESTRO_INVERSION T1
    INNER JOIN SACIF_MYP.CRONOGRAMA_PAGO T2 ON T1.NINVERSION=T2.NINVERSION AND T2.NCUOTA=1
    INNER JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF_MYP.ESTADO_CUENTA_TCHN 
    GROUP BY NINVERSION) T3 ON T1.NINVERSION=T3.NINVERSION
    INNER JOIN SACIF_MYP.ESTADO_CUENTA_TCHN T4 ON T1.NINVERSION=T4.NINVERSION AND T3.NINVERSION=T4.NINVERSION AND T3.NSECUENCIA=T4.NSECUENCIA

    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0002','0001',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0002','0001',TIPOCARTA)) T50 ON T50.TIPOCARTA IN('0001','0002') AND TRIM(T50.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0009','0007',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0009','0007',TIPOCARTA)) T54 ON T54.TIPOCARTA IN('0007','0009') AND TRIM(T54.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, DECODE(TIPOCARTA,'0010','0008',TIPOCARTA) TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, DECODE(TIPOCARTA,'0010','0008',TIPOCARTA)) T55 ON T55.TIPOCARTA IN('0008','0010') AND TRIM(T55.DVALOR_BV)=TRIM(T1.DVALOR_BV)


    LEFT JOIN (SELECT DVALOR_BV, TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, TIPOCARTA) T52 ON T52.TIPOCARTA='0003' AND TRIM(T52.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    LEFT JOIN (SELECT DVALOR_BV, TIPOCARTA, MAX(FEMISION) FEMISION, COUNT(*) CANT_REI FROM CTDIA.MOVIMIENTO_CARTAS
    WHERE DOC_TIPO='CN' AND TIPOFORMATO='0001' GROUP BY DVALOR_BV, TIPOCARTA) T53 ON T53.TIPOCARTA='0004' AND TRIM(T53.DVALOR_BV)=TRIM(T1.DVALOR_BV)

    LEFT JOIN CTDIA.MOVIMIENTO_PROTESTO T90 ON T90.DOC_TIPO='PN' AND TRIM(T90.DVALOR_BV)=TRIM(T1.DVALOR_BV)

    LEFT JOIN (SELECT NINVERSION, MAX(NSECUENCIA) NSECUENCIA FROM SACIF_MYP.ESTADO_CUENTA_TCHN WHERE MABONO<>0
    GROUP BY NINVERSION) T6 ON T1.NINVERSION=T6.NINVERSION
    LEFT JOIN SACIF_MYP.ESTADO_CUENTA_TCHN T7 ON T1.NINVERSION=T7.NINVERSION AND T6.NSECUENCIA=T7.NSECUENCIA

    LEFT JOIN (
    SELECT 
    T1.CFOND,
    T1.NINVERSION,
    COUNT(T3.MCARGO) NRO_2CUOTAS_ATRAS
    FROM SACIF_MYP.MAESTRO_INVERSION T1
    INNER JOIN SACIF_MYP.CRONOGRAMA_PAGO T2 ON T1.NINVERSION=T2.NINVERSION AND T2.NCUOTA=1
    INNER JOIN SACIF_MYP.ESTADO_CUENTA_TCHN T3 ON T1.NINVERSION=T3.NINVERSION AND T3.CCONCEPTO='0001' AND T3.DOPERACION>=(SYSDATE-10080)
    WHERE NVL(T1.FCANCELADO,'N')='N'  AND NVL(T1.FJUDICIAL,'N')='N'
    AND TRUNC(T3.MSALDO*-1) >= TRUNC(T2.MCUOTA*2)
    AND TRUNC(T3.MSALDO*-1) < TRUNC(T2.MCUOTA*3)
    GROUP BY T1.CFOND, T1.NINVERSION
    ) T8 ON T1.CFOND=T8.CFOND AND T1.NINVERSION=T8.NINVERSION

    LEFT JOIN (
    SELECT DVALOR_BV, S_TCHN
    FROM CTDIA.MAE_CUSTODIA WHERE C_FONDO_ID='0003' AND DOCUMENTO_ID='0015'
    ) T10 ON TRIM(T1.DVALOR_BV)=TRIM(T10.DVALOR_BV)
    LEFT JOIN (
    SELECT  DVALOR_BV,S_ASHIPO,S_PEHIPO,S_ASEXPTCHN
    FROM CTDIA.MAE_CUSTODIA WHERE C_FONDO_ID='0003' AND DOCUMENTO_ID='0014'
    ) T11 ON  TRIM(T1.DVALOR_BV)=TRIM(T11.DVALOR_BV)

    LEFT JOIN (
        SELECT NINVERSION, ROUND(AVG(DIAS)) FRECUENCIA_PAGO  FROM
        (
            SELECT 
            Q1.NINVERSION,
            Q1.NSECUENCIA,
            Q1.MABONO,
            Q1.MCARGO,
            Q1.MSALDO,
            MAX(Q2.DOPERACION) DOPERACION_ANTE,
            Q1.DOPERACION,
            Q1.DOPERACION-MAX(Q2.DOPERACION) DIAS
            FROM SACIF_POP.ESTADO_CUENTA_TCHN Q1 
            INNER JOIN SACIF_POP.ESTADO_CUENTA_TCHN Q2 ON Q1.NINVERSION=Q2.NINVERSION AND Q1.NSECUENCIA>Q2.NSECUENCIA AND Q2.CCONCEPTO='0002'
            WHERE  Q1.CCONCEPTO='0002'
            GROUP BY Q1.NINVERSION,
            Q1.NSECUENCIA,
            Q1.DOPERACION,
            Q1.MABONO,
            Q1.MCARGO,
            Q1.MSALDO
            HAVING Q1.DOPERACION-MAX(Q2.DOPERACION)>15
            ORDER BY Q1.NSECUENCIA
        ) GROUP BY NINVERSION
    ) T12 ON  T1.NINVERSION=T12.NINVERSION

    WHERE NVL(T1.FCANCELADO,'N')='N' AND NVL(T1.FJUDICIAL,'N')='N' AND NVL(T1.EXTRAJUDICIAL,'N')='N'  

    ;


  BEGIN

  FOR I1 IN C1 LOOP
   INSERT INTO TEMP_REQ_CRITERIOS
   (COD_FONDO,
	DVALOR_BV,
	CUOTA_VEN_TOT,
	ULT_PAGO,
	DIAS_SINPAGO,
	CANT_2CUOTA_ATRAS,
	FRECUENCIA_PAGO,
	CON_TCHN,
	CON_ASHIPO,
	CARTA_NOTARIAL_F1,
	CARTA_NOTARIAL_R1,
	CARTA_NOTARIAL_O1,
	CARTA_NOTARIAL_F2,
	CARTA_NOTARIAL_R2,
	CARTA_NOTARIAL_O2,
	CARTA_NOTARIAL_F3,
	CARTA_NOTARIAL_R3,
	CARTA_NOTARIAL_O3,    
	PROTESTO_NOTARIAL_F,
	PROTESTO_NOTARIAL_R,
	PROTESTO_NOTARIAL_O,
	CARTA_PROTESTO_F,
	CARTA_PROTESTO_R,
	CARTA_PROTESTO_O,
	CARTA_PREJECUCION_F,
	CARTA_PREJECUCION_R,
	CARTA_PREJECUCION_O,
    CUOTA_TOTAL,
    CUOTA_GENERADA,
    CUOTA_DIA
   )
   VALUES(
    I1.CFOND,
    I1.DVALOR_BV, 
    I1.CUOTAS,
    I1.ULT_PAGO,
    I1.DIAS_SINPAGO,
    I1.NRO_2CUOTAS_ATRAS,
    I1.FRECUENCIA_PAGO,
    I1.S_TCHN,
    I1.S_ASHIPO,

    I1.CARTA_NOTARIAL_F1,
    I1.CARTA_NOTARIAL_R1,
	I1.CARTA_NOTARIAL_O1,

    I1.CARTA_NOTARIAL_F2,
    I1.CARTA_NOTARIAL_R2,
	I1.CARTA_NOTARIAL_O2,

    I1.CARTA_NOTARIAL_F3,
    I1.CARTA_NOTARIAL_R3,
	I1.CARTA_NOTARIAL_O3,    

	I1.PROTESTO_NOTARIAL_F1,
	NULL,
	I1.PROTESTO_NOTARIAL_O1,
	I1.CARTA_PROTESTO_F1,
	I1.CARTA_PROTESTO_R1,
	I1.CARTA_PROTESTO_O1,
	I1.CARTA_PREJECUCION_F1,
	I1.CARTA_PREJECUCION_R1,
	I1.CARTA_PREJECUCION_O1,
    I1.NPLAZO_MESES, 
    I1.NCUOTAS_GENERADAS,
    I1.CUOTA_DIA
   );
  END LOOP;


     OPEN P_RESULTADO FOR

     SELECT TR2.PRIORI, TR1.* FROM (

     SELECT F1.* FROM (

     --CRONOGRAMA VIGENTE
     SELECT 
        T2.D_ABREVIADO D_FONDO,
        T4.TAPATERNO, 
        T4.TAMATERNO, 
        SUBSTR(T4.TNOMBRES,0,1)||'.' TNOMBRES,
        T1.COD_FONDO,
        T1.DVALOR_BV,
        T1.CUOTA_VEN_TOT,
        T1.ULT_PAGO,
        T1.DIAS_SINPAGO,
        T1.CANT_2CUOTA_ATRAS,
        T1.FRECUENCIA_PAGO,
        T1.CON_TCHN,
        T1.CON_ASHIPO,
        T1.CUOTA_TOTAL,
        T1.CUOTA_GENERADA,
        T1.CUOTA_DIA,
        T4.FVCTO,
        T1.CARTA_NOTARIAL_F1,
        T1.CARTA_NOTARIAL_R1,
        T1.CARTA_NOTARIAL_O1,
        T1.CARTA_NOTARIAL_F2,
        T1.CARTA_NOTARIAL_R2,
        T1.CARTA_NOTARIAL_O2,
        T1.CARTA_NOTARIAL_F3,
        T1.CARTA_NOTARIAL_R3,
        T1.CARTA_NOTARIAL_O3,
        T1.PROTESTO_NOTARIAL_F,
        T1.PROTESTO_NOTARIAL_R,
        T1.PROTESTO_NOTARIAL_O,
        T1.CARTA_PROTESTO_F,
        T1.CARTA_PROTESTO_R,
        T1.CARTA_PROTESTO_O,
        T1.CARTA_PREJECUCION_F,
        T1.CARTA_PREJECUCION_R,
        T1.CARTA_PREJECUCION_O,

        CASE 
        --PRIMERA CARTA CON TCHN, ASIENTO Y AMBOS
        WHEN T1.CARTA_NOTARIAL_F1 IS NULL AND
             T1.CARTA_NOTARIAL_R1 IS NULL AND
             T1.CARTA_NOTARIAL_O1 IS NULL AND
             T1.CARTA_NOTARIAL_F2 IS NULL AND
             T1.CARTA_NOTARIAL_R2 IS NULL AND
             T1.CARTA_NOTARIAL_O2 IS NULL AND
             T1.CARTA_NOTARIAL_F3 IS NULL AND
             T1.CARTA_NOTARIAL_R3 IS NULL AND
             T1.CARTA_NOTARIAL_O3 IS NULL AND
             T1.PROTESTO_NOTARIAL_F IS NULL AND
             T1.PROTESTO_NOTARIAL_R IS NULL AND
             T1.PROTESTO_NOTARIAL_O IS NULL AND
             T1.CARTA_PROTESTO_F IS NULL AND
             T1.CARTA_PROTESTO_R IS NULL AND
             T1.CARTA_PROTESTO_O IS NULL AND
             T1.CARTA_PREJECUCION_F IS NULL AND
             T1.CARTA_PREJECUCION_R IS NULL AND
             T1.CARTA_PREJECUCION_O IS NULL 
        THEN 

            CASE 
                WHEN T1.CON_TCHN IS NOT NULL AND T1.CON_ASHIPO IS NOT NULL THEN '0001' 
                WHEN T1.CON_TCHN IS NULL AND T1.CON_ASHIPO IS NOT NULL THEN '0007' 
                WHEN T1.CON_TCHN IS NULL AND T1.CON_ASHIPO IS NULL THEN '0008'         
            END

        --REITERO DE PRIMERA CARTA CON TCHN, ASIENTO Y AMBOS
        WHEN (
                    (T1.CARTA_NOTARIAL_F1 IS NOT NULL AND T1.CARTA_NOTARIAL_O1 IS NOT NULL)
                    OR (T1.CARTA_NOTARIAL_F2 IS NOT NULL AND T1.CARTA_NOTARIAL_O2 IS NOT NULL)
                    OR (T1.CARTA_NOTARIAL_F3 IS NOT NULL AND T1.CARTA_NOTARIAL_O3 IS NOT NULL)   
            ) AND
             T1.CON_TCHN IS NULL AND
             T1.PROTESTO_NOTARIAL_F IS NULL AND
             T1.PROTESTO_NOTARIAL_R IS NULL AND
             T1.PROTESTO_NOTARIAL_O IS NULL AND
             T1.CARTA_PROTESTO_F IS NULL AND
             T1.CARTA_PROTESTO_R IS NULL AND
             T1.CARTA_PROTESTO_O IS NULL AND
             T1.CARTA_PREJECUCION_F IS NULL AND
             T1.CARTA_PREJECUCION_R IS NULL AND
             T1.CARTA_PREJECUCION_O IS NULL  
       THEN
            CASE 
                WHEN T1.CON_TCHN IS NOT NULL AND T1.CON_ASHIPO IS NOT NULL THEN '0002' 
                WHEN T1.CON_TCHN IS NULL AND T1.CON_ASHIPO IS NOT NULL THEN '0006' 
                WHEN T1.CON_TCHN IS NULL AND T1.CON_ASHIPO IS NULL THEN '0009'         
            END

        --PROTESTO NOTARIAL    
        WHEN        
            (
                (T1.CARTA_NOTARIAL_F1 IS NOT NULL AND T1.CARTA_NOTARIAL_O1 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F2 IS NOT NULL AND T1.CARTA_NOTARIAL_O2 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F3 IS NOT NULL AND T1.CARTA_NOTARIAL_O3 IS NOT NULL)   
            ) AND

            T1.CON_TCHN IS NOT NULL AND        
            T1.PROTESTO_NOTARIAL_F IS NULL AND
            T1.PROTESTO_NOTARIAL_R IS NULL AND
            T1.PROTESTO_NOTARIAL_O IS NULL AND
            T1.CARTA_PROTESTO_F IS NULL AND
            T1.CARTA_PROTESTO_R IS NULL AND
            T1.CARTA_PROTESTO_O IS NULL AND
            T1.CARTA_PREJECUCION_F IS NULL AND
            T1.CARTA_PREJECUCION_R IS NULL AND
            T1.CARTA_PREJECUCION_O IS NULL  
        THEN

            CASE 
            WHEN T1.CUOTA_VEN_TOT>=3 AND 
                TRUNC(SYSDATE)>= T4.DPAGO_CRONO AND
                TRUNC(SYSDATE)<= T4.DPAGO_CRONO+6
            THEN  '0005' 
            ELSE '2000'
            END

        --CARTA DE PROTESTO
        WHEN 
            (
                (T1.CARTA_NOTARIAL_F1 IS NOT NULL AND T1.CARTA_NOTARIAL_O1 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F2 IS NOT NULL AND T1.CARTA_NOTARIAL_O2 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F3 IS NOT NULL AND T1.CARTA_NOTARIAL_O3 IS NOT NULL)   
            ) AND

            T1.CON_TCHN IS NOT NULL AND
            T1.PROTESTO_NOTARIAL_F IS NOT NULL AND
            T1.PROTESTO_NOTARIAL_O IS NOT NULL AND        
            T1.CARTA_PROTESTO_F IS NULL AND
            T1.CARTA_PROTESTO_R IS NULL AND
            T1.CARTA_PROTESTO_O IS NULL AND        
            T1.CARTA_PREJECUCION_F IS NULL AND
            T1.CARTA_PREJECUCION_R IS NULL AND
            T1.CARTA_PREJECUCION_O IS NULL
        THEN
            '0003' 

        --CARTA DE PRE EJECUCION
        WHEN
             (
                (T1.CARTA_NOTARIAL_F1 IS NOT NULL AND T1.CARTA_NOTARIAL_O1 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F2 IS NOT NULL AND T1.CARTA_NOTARIAL_O2 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F3 IS NOT NULL AND T1.CARTA_NOTARIAL_O3 IS NOT NULL)   
            ) AND

            T1.CON_TCHN IS NOT NULL AND
            T1.PROTESTO_NOTARIAL_F IS NOT NULL AND
            T1.PROTESTO_NOTARIAL_O IS NOT NULL AND        
            T1.CARTA_PROTESTO_F IS NOT NULL AND
            T1.CARTA_PROTESTO_O IS NOT NULL AND        
            T1.CARTA_PREJECUCION_F IS NULL AND
            T1.CARTA_PREJECUCION_R IS NULL AND
            T1.CARTA_PREJECUCION_O IS NULL 
    THEN
        CASE WHEN T1.CUOTA_VEN_TOT>=7 THEN '0004'
        ELSE '2000'
        END

    --REITERO DE CARTA DE PRE EJECUCION    
    WHEN        
            (
                (T1.CARTA_NOTARIAL_F1 IS NOT NULL AND T1.CARTA_NOTARIAL_O1 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F2 IS NOT NULL AND T1.CARTA_NOTARIAL_O2 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F3 IS NOT NULL AND T1.CARTA_NOTARIAL_O3 IS NOT NULL)   
            ) AND

            T1.CON_TCHN IS NOT NULL AND
            T1.PROTESTO_NOTARIAL_F IS NOT NULL AND
            T1.PROTESTO_NOTARIAL_O IS NOT NULL AND
            T1.CARTA_PROTESTO_F IS NOT NULL AND
            T1.CARTA_PROTESTO_O IS NOT NULL AND
            T1.CARTA_PREJECUCION_F IS NOT NULL AND
            T1.CARTA_PREJECUCION_O IS NOT NULL AND
            NVL(T1.CARTA_PREJECUCION_R,0) < 2

        THEN
            CASE WHEN T1.CUOTA_VEN_TOT>=7 THEN '0004'
            ELSE '2000'
            END
        ELSE 
            '1000' 
        END TIPO_CARTA

     FROM TEMP_REQ_CRITERIOS T1 
     INNER JOIN MAE_FONDO T2 ON T1.COD_FONDO=T2.C_FONDO_ID     
     INNER JOIN (    
        SELECT '0001' C_FONDO_ID, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I1.FVCTO, I4.DPAGO_CRONO
        FROM SACIF.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF.MAESTRO_INVERSION I3 ON I1.DVALOR_BV=I3.DVALOR_BV
        LEFT JOIN (SELECT NINVERSION, MAX(DPAGO_CRONO) DPAGO_CRONO FROM SACIF.CUOTA_PAGO GROUP BY NINVERSION) I4 ON I3.NINVERSION=I4.NINVERSION 

        UNION ALL

        SELECT '0002' C_FONDO_ID, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I1.FVCTO, I4.DPAGO_CRONO 
        FROM SACIF_POP.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_POP.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF_POP.MAESTRO_INVERSION I3 ON I1.DVALOR_BV=I3.DVALOR_BV
        LEFT JOIN (SELECT NINVERSION, MAX(DPAGO_CRONO) DPAGO_CRONO FROM SACIF_POP.CUOTA_PAGO GROUP BY NINVERSION) I4 ON I3.NINVERSION=I4.NINVERSION         

        UNION ALL

        SELECT '0003' C_FONDO_ID, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I1.FVCTO, I4.DPAGO_CRONO 
        FROM SACIF_MYP.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_MYP.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF_MYP.MAESTRO_INVERSION I3 ON I1.DVALOR_BV=I3.DVALOR_BV
        LEFT JOIN (SELECT NINVERSION, MAX(DPAGO_CRONO) DPAGO_CRONO FROM SACIF_MYP.CUOTA_PAGO GROUP BY NINVERSION) I4 ON I3.NINVERSION=I4.NINVERSION                 

        UNION ALL

        SELECT '0004' C_FONDO_ID, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I1.FVCTO, I4.DPAGO_CRONO 
        FROM SACIF_PRH.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_PRH.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA 
        INNER JOIN SACIF_PRH.MAESTRO_INVERSION I3 ON I1.DVALOR_BV=I3.DVALOR_BV
        LEFT JOIN (SELECT NINVERSION, MAX(DPAGO_CRONO) DPAGO_CRONO FROM SACIF_PRH.CUOTA_PAGO GROUP BY NINVERSION) I4 ON I3.NINVERSION=I4.NINVERSION                         
    ) T4 ON T4.C_FONDO_ID=T1.COD_FONDO AND TRIM(T4.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    WHERE T1.CUOTA_VEN_TOT>=2    
    AND T1.CUOTA_GENERADA<=T1.CUOTA_TOTAL   


    UNION ALL

     --CRONOGRAMA VENCIDO
     SELECT 
        T2.D_ABREVIADO D_FONDO,
        T4.TAPATERNO, 
        T4.TAMATERNO, 
        SUBSTR(T4.TNOMBRES,0,1)||'.' TNOMBRES,
        T1.COD_FONDO,
        T1.DVALOR_BV,
        T1.CUOTA_VEN_TOT,
        T1.ULT_PAGO,
        T1.DIAS_SINPAGO,
        T1.CANT_2CUOTA_ATRAS,
        T1.FRECUENCIA_PAGO,
        T1.CON_TCHN,
        T1.CON_ASHIPO,
        T1.CUOTA_TOTAL,
        T1.CUOTA_GENERADA,
        T1.CUOTA_DIA,
        T4.FVCTO,
        T1.CARTA_NOTARIAL_F1,
        T1.CARTA_NOTARIAL_R1,
        T1.CARTA_NOTARIAL_O1,
        T1.CARTA_NOTARIAL_F2,
        T1.CARTA_NOTARIAL_R2,
        T1.CARTA_NOTARIAL_O2,
        T1.CARTA_NOTARIAL_F3,
        T1.CARTA_NOTARIAL_R3,
        T1.CARTA_NOTARIAL_O3,
        T1.PROTESTO_NOTARIAL_F,
        T1.PROTESTO_NOTARIAL_R,
        T1.PROTESTO_NOTARIAL_O,
        T1.CARTA_PROTESTO_F,
        T1.CARTA_PROTESTO_R,
        T1.CARTA_PROTESTO_O,
        T1.CARTA_PREJECUCION_F,
        T1.CARTA_PREJECUCION_R,
        T1.CARTA_PREJECUCION_O,

        CASE 
        --PRIMERA CARTA CON TCHN, ASIENTO Y AMBOS
        WHEN T1.CARTA_NOTARIAL_F1 IS NULL AND
             T1.CARTA_NOTARIAL_R1 IS NULL AND
             T1.CARTA_NOTARIAL_O1 IS NULL AND
             T1.CARTA_NOTARIAL_F2 IS NULL AND
             T1.CARTA_NOTARIAL_R2 IS NULL AND
             T1.CARTA_NOTARIAL_O2 IS NULL AND
             T1.CARTA_NOTARIAL_F3 IS NULL AND
             T1.CARTA_NOTARIAL_R3 IS NULL AND
             T1.CARTA_NOTARIAL_O3 IS NULL AND
             T1.PROTESTO_NOTARIAL_F IS NULL AND
             T1.PROTESTO_NOTARIAL_R IS NULL AND
             T1.PROTESTO_NOTARIAL_O IS NULL AND
             T1.CARTA_PROTESTO_F IS NULL AND
             T1.CARTA_PROTESTO_R IS NULL AND
             T1.CARTA_PROTESTO_O IS NULL AND
             T1.CARTA_PREJECUCION_F IS NULL AND
             T1.CARTA_PREJECUCION_R IS NULL AND
             T1.CARTA_PREJECUCION_O IS NULL 
        THEN 

            CASE 
                WHEN T1.CON_TCHN IS NOT NULL AND T1.CON_ASHIPO IS NOT NULL THEN '0001' 
                WHEN T1.CON_TCHN IS NULL AND T1.CON_ASHIPO IS NOT NULL THEN '0007' 
                WHEN T1.CON_TCHN IS NULL AND T1.CON_ASHIPO IS NULL THEN '0008'         
            END

        --REITERO DE PRIMERA CARTA CON TCHN, ASIENTO Y AMBOS
        WHEN (
                    (T1.CARTA_NOTARIAL_F1 IS NOT NULL AND T1.CARTA_NOTARIAL_O1 IS NOT NULL)
                    OR (T1.CARTA_NOTARIAL_F2 IS NOT NULL AND T1.CARTA_NOTARIAL_O2 IS NOT NULL)
                    OR (T1.CARTA_NOTARIAL_F3 IS NOT NULL AND T1.CARTA_NOTARIAL_O3 IS NOT NULL)   
            ) AND
             T1.CON_TCHN IS NULL AND
             T1.PROTESTO_NOTARIAL_F IS NULL AND
             T1.PROTESTO_NOTARIAL_R IS NULL AND
             T1.PROTESTO_NOTARIAL_O IS NULL AND
             T1.CARTA_PROTESTO_F IS NULL AND
             T1.CARTA_PROTESTO_R IS NULL AND
             T1.CARTA_PROTESTO_O IS NULL AND
             T1.CARTA_PREJECUCION_F IS NULL AND
             T1.CARTA_PREJECUCION_R IS NULL AND
             T1.CARTA_PREJECUCION_O IS NULL  
       THEN
            CASE 
                WHEN T1.CON_TCHN IS NOT NULL AND T1.CON_ASHIPO IS NOT NULL THEN '0002' 
                WHEN T1.CON_TCHN IS NULL AND T1.CON_ASHIPO IS NOT NULL THEN '0006' 
                WHEN T1.CON_TCHN IS NULL AND T1.CON_ASHIPO IS NULL THEN '0009'         
            END

        --PROTESTO NOTARIAL    
        WHEN        
            (
                (T1.CARTA_NOTARIAL_F1 IS NOT NULL AND T1.CARTA_NOTARIAL_O1 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F2 IS NOT NULL AND T1.CARTA_NOTARIAL_O2 IS NOT NULL)
             OR (T1.CARTA_NOTARIAL_F3 IS NOT NULL AND T1.CARTA_NOTARIAL_O3 IS NOT NULL)   
            ) AND

            T1.CON_TCHN IS NOT NULL AND        
            T1.PROTESTO_NOTARIAL_F IS NULL AND
            T1.PROTESTO_NOTARIAL_R IS NULL AND
            T1.PROTESTO_NOTARIAL_O IS NULL AND
            T1.CARTA_PROTESTO_F IS NULL AND
            T1.CARTA_PROTESTO_R IS NULL AND
            T1.CARTA_PROTESTO_O IS NULL AND
            T1.CARTA_PREJECUCION_F IS NULL AND
            T1.CARTA_PREJECUCION_R IS NULL AND
            T1.CARTA_PREJECUCION_O IS NULL  
        THEN

            CASE   
            WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=2 AND T1.CUOTA_DIA<=28  AND 
                TRUNC(SYSDATE)>= TO_DATE(T1.CUOTA_DIA||'/'||TO_CHAR(SYSDATE,'MM')||'/'||TO_CHAR(SYSDATE,'YYYY'),'DD/MM/YYYY') AND
                TRUNC(SYSDATE)<= TO_DATE(T1.CUOTA_DIA||'/'||TO_CHAR(SYSDATE,'MM')||'/'||TO_CHAR(SYSDATE,'YYYY'),'DD/MM/YYYY')+6
            THEN  '0005' 
            WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))<>2  AND 
                TRUNC(SYSDATE)>= TO_DATE(T1.CUOTA_DIA||'/'||TO_CHAR(SYSDATE,'MM')||'/'||TO_CHAR(SYSDATE,'YYYY'),'DD/MM/YYYY') AND
                TRUNC(SYSDATE)<= TO_DATE(T1.CUOTA_DIA||'/'||TO_CHAR(SYSDATE,'MM')||'/'||TO_CHAR(SYSDATE,'YYYY'),'DD/MM/YYYY')+6                
            THEN  '0005' 

            ELSE '2000'
            END              

        ELSE 
            '1000' 
        END TIPO_CARTA

     FROM TEMP_REQ_CRITERIOS T1 
     INNER JOIN MAE_FONDO T2 ON T1.COD_FONDO=T2.C_FONDO_ID     
     INNER JOIN (    
        SELECT '0001' C_FONDO_ID, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I1.FVCTO, I4.DPAGO_CRONO  
        FROM SACIF.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF.MAESTRO_INVERSION I3 ON I1.DVALOR_BV=I3.DVALOR_BV
        LEFT JOIN (SELECT NINVERSION, MAX(DPAGO_CRONO) DPAGO_CRONO FROM SACIF.CUOTA_PAGO GROUP BY NINVERSION) I4 ON I3.NINVERSION=I4.NINVERSION                                 

        UNION ALL

        SELECT '0002' C_FONDO_ID, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I1.FVCTO, I4.DPAGO_CRONO  
        FROM SACIF_POP.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_POP.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF_POP.MAESTRO_INVERSION I3 ON I1.DVALOR_BV=I3.DVALOR_BV
        LEFT JOIN (SELECT NINVERSION, MAX(DPAGO_CRONO) DPAGO_CRONO FROM SACIF_POP.CUOTA_PAGO GROUP BY NINVERSION) I4 ON I3.NINVERSION=I4.NINVERSION                                         

        UNION ALL

        SELECT '0003' C_FONDO_ID, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I1.FVCTO, I4.DPAGO_CRONO  
        FROM SACIF_MYP.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_MYP.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA
        INNER JOIN SACIF_MYP.MAESTRO_INVERSION I3 ON I1.DVALOR_BV=I3.DVALOR_BV
        LEFT JOIN (SELECT NINVERSION, MAX(DPAGO_CRONO) DPAGO_CRONO FROM SACIF_MYP.CUOTA_PAGO GROUP BY NINVERSION) I4 ON I3.NINVERSION=I4.NINVERSION                                         

        UNION ALL

        SELECT '0004' C_FONDO_ID, I1.DVALOR_BV,  I2.TAPATERNO, I2.TAMATERNO, I2.TNOMBRES, I1.FVCTO, I4.DPAGO_CRONO  
        FROM SACIF_PRH.ALTERNATIVA_INVERSION I1
        INNER JOIN SACIF_PRH.PERSONA I2 ON I1.CPERSONA=I2.CPERSONA 
        INNER JOIN SACIF_PRH.MAESTRO_INVERSION I3 ON I1.DVALOR_BV=I3.DVALOR_BV
        LEFT JOIN (SELECT NINVERSION, MAX(DPAGO_CRONO) DPAGO_CRONO FROM SACIF_PRH.CUOTA_PAGO GROUP BY NINVERSION) I4 ON I3.NINVERSION=I4.NINVERSION                                         
        
    ) T4 ON T4.C_FONDO_ID=T1.COD_FONDO AND TRIM(T4.DVALOR_BV)=TRIM(T1.DVALOR_BV)
    WHERE T1.CUOTA_VEN_TOT>=1    
    AND (T1.CUOTA_GENERADA+1)>T1.CUOTA_TOTAL      




    ) F1

    LEFT JOIN COB_REQ_CARTAS F2 ON F1.COD_FONDO=F2.FONDO_ID AND TRIM(F1.DVALOR_BV)=TRIM(F2.DVALOR_BV) AND F2.IS_DELETE='N' AND F2.REQ_ESTADO IN('0001','0002')
    WHERE F2.REQ_ESTADO IS NULL

    ) TR1 LEFT JOIN  COB_TABLAS TR2 ON TR2.C_TABLA_ID='0622' AND TR2.C_TABLA_DET_ID=TR1.TIPO_CARTA
    ORDER BY TR2.PRIORI, TR1.COD_FONDO,  TR1.DVALOR_BV DESC

    ; 


  END SP_REQ_SUGERIDOS;


  PROCEDURE SP_CREAR_REQUERIMIENTO(
    P_REQ_TIPO COB_REQ_CARTAS.REQ_TIPO%TYPE,
	P_REQ_NUMERO COB_REQ_CARTAS.REQ_NUMERO%TYPE,
	P_FONDO_ID COB_REQ_CARTAS.FONDO_ID%TYPE,
	P_DVALOR_BV COB_REQ_CARTAS.DVALOR_BV%TYPE,
	P_REQ_EMISION COB_REQ_CARTAS.REQ_EMISION%TYPE,
	P_TIPO_CARTA COB_REQ_CARTAS.TIPO_CARTA%TYPE,
	P_REQ_COMENTARIO COB_REQ_CARTAS.REQ_COMENTARIO%TYPE,
	P_C_USUARIO_ADD COB_REQ_CARTAS.C_USUARIO_ADD%TYPE,
	P_CUOTA_VEN_TOT COB_REQ_CRITERIOS.CUOTA_VEN_TOT%TYPE,
	P_ULT_PAGO COB_REQ_CRITERIOS.ULT_PAGO%TYPE,
	P_DIAS_SINPAGO COB_REQ_CRITERIOS.DIAS_SINPAGO%TYPE,
	P_CANT_2CUOTA_ATRAS COB_REQ_CRITERIOS.CANT_2CUOTA_ATRAS%TYPE,
	P_FRECUENCIA_PAGO COB_REQ_CRITERIOS.FRECUENCIA_PAGO%TYPE,
	P_CON_TCHN COB_REQ_CRITERIOS.CON_TCHN%TYPE,
	P_CON_ASHIPO COB_REQ_CRITERIOS.CON_ASHIPO%TYPE,
	P_CUOTA_TOTAL COB_REQ_CRITERIOS.CUOTA_TOTAL%TYPE,    
	P_CUOTA_GENERADA COB_REQ_CRITERIOS.CUOTA_GENERADA%TYPE, 
    P_CUOTA_DIA COB_REQ_CRITERIOS.CUOTA_DIA%TYPE, 

	P_CARTA_NOTARIAL_F1 COB_REQ_CRITERIOS.CARTA_NOTARIAL_F1%TYPE,
	P_CARTA_NOTARIAL_R1 COB_REQ_CRITERIOS.CARTA_NOTARIAL_R1%TYPE, 
	P_CARTA_NOTARIAL_O1 COB_REQ_CRITERIOS.CARTA_NOTARIAL_O1%TYPE,
	P_CARTA_NOTARIAL_F2 COB_REQ_CRITERIOS.CARTA_NOTARIAL_F2%TYPE,
	P_CARTA_NOTARIAL_R2 COB_REQ_CRITERIOS.CARTA_NOTARIAL_R2%TYPE,
	P_CARTA_NOTARIAL_O2 COB_REQ_CRITERIOS.CARTA_NOTARIAL_O2%TYPE,
	P_CARTA_NOTARIAL_F3 COB_REQ_CRITERIOS.CARTA_NOTARIAL_F3%TYPE,
	P_CARTA_NOTARIAL_R3 COB_REQ_CRITERIOS.CARTA_NOTARIAL_R3%TYPE,
	P_CARTA_NOTARIAL_O3 COB_REQ_CRITERIOS.CARTA_NOTARIAL_O3%TYPE,
	P_PROTESTO_NOTARIAL_F1 COB_REQ_CRITERIOS.PROTESTO_NOTARIAL_F1%TYPE,
	P_PROTESTO_NOTARIAL_R1 COB_REQ_CRITERIOS.PROTESTO_NOTARIAL_R1%TYPE,
	P_PROTESTO_NOTARIAL_O1 COB_REQ_CRITERIOS.PROTESTO_NOTARIAL_O1%TYPE,
	P_CARTA_PROTESTO_F1 COB_REQ_CRITERIOS.CARTA_PROTESTO_F1%TYPE,
	P_CARTA_PROTESTO_R1 COB_REQ_CRITERIOS.CARTA_PROTESTO_R1%TYPE,
	P_CARTA_PROTESTO_O1 COB_REQ_CRITERIOS.CARTA_PROTESTO_O1%TYPE,
	P_CARTA_PREJECUCION_F1 COB_REQ_CRITERIOS.CARTA_PREJECUCION_F1%TYPE,
	P_CARTA_PREJECUCION_R1 COB_REQ_CRITERIOS.CARTA_PREJECUCION_R1%TYPE,
	P_CARTA_PREJECUCION_O1 COB_REQ_CRITERIOS.CARTA_PREJECUCION_O1%TYPE,


    P_RESULTADO OUT cursorType
    ) AS

    VDOC_NUM DOC_NUMERADOR.DOC_NUM%TYPE;
    err_num NUMBER;
    err_msg VARCHAR2(255);    
  BEGIN

        SELECT DOC_NUM+1 INTO VDOC_NUM FROM DOC_NUMERADOR WHERE DOC_TIPO='RC';
        UPDATE DOC_NUMERADOR SET DOC_NUM=VDOC_NUM WHERE DOC_TIPO='RC';

        INSERT INTO COB_REQ_CARTAS
      ( REQ_TIPO,
        REQ_NUMERO,
        FONDO_ID,
        DVALOR_BV,
        REQ_EMISION,
        TIPO_CARTA,
        REQ_ESTADO,
        REQ_COMENTARIO,
        C_USUARIO_ADD,
        F_USUARIO_ADD,
        C_USUARIO_MOD,
        F_USUARIO_MOD,
        REQ_ENVIO,
        REQ_RECEPCION,
        IS_DELETE
        )
        VALUES(
            'RC',
            VDOC_NUM,
            P_FONDO_ID,
            P_DVALOR_BV,
            trunc(SYSDATE),
            P_TIPO_CARTA,
            '0001',
            P_REQ_COMENTARIO,
            P_C_USUARIO_ADD,
            SYSDATE,
            NULL,
            NULL,
            NULL,
            NULL,
            'N'
        );

        INSERT INTO COB_REQ_CRITERIOS(	
            REQ_TIPO,
            REQ_NUMERO,
            CRI_ITEM,
            CUOTA_VEN_TOT,
            ULT_PAGO,
            DIAS_SINPAGO,
            CANT_2CUOTA_ATRAS,
            FRECUENCIA_PAGO,
            CON_TCHN,
            CON_ASHIPO,
            CUOTA_TOTAL,
            CUOTA_GENERADA,
            CUOTA_DIA,
            CARTA_NOTARIAL_F1,
            CARTA_NOTARIAL_R1,
            CARTA_NOTARIAL_O1,
            CARTA_NOTARIAL_F2,
            CARTA_NOTARIAL_R2,
            CARTA_NOTARIAL_O2,
            CARTA_NOTARIAL_F3,
            CARTA_NOTARIAL_R3,
            CARTA_NOTARIAL_O3,
            PROTESTO_NOTARIAL_F1,
            PROTESTO_NOTARIAL_R1,
            PROTESTO_NOTARIAL_O1,
            CARTA_PROTESTO_F1,
            CARTA_PROTESTO_R1,
            CARTA_PROTESTO_O1,
            CARTA_PREJECUCION_F1,
            CARTA_PREJECUCION_R1,
            CARTA_PREJECUCION_O1
        )
        VALUES(
            'RC',
            VDOC_NUM,
            1,
            P_CUOTA_VEN_TOT,
            P_ULT_PAGO,
            P_DIAS_SINPAGO,
            P_CANT_2CUOTA_ATRAS,
            P_FRECUENCIA_PAGO,
            P_CON_TCHN,
            P_CON_ASHIPO,
            P_CUOTA_TOTAL,
            P_CUOTA_GENERADA,
            P_CUOTA_DIA,
            P_CARTA_NOTARIAL_F1,
            P_CARTA_NOTARIAL_R1,
            P_CARTA_NOTARIAL_O1,
            P_CARTA_NOTARIAL_F2,
            P_CARTA_NOTARIAL_R2,
            P_CARTA_NOTARIAL_O2,
            P_CARTA_NOTARIAL_F3,
            P_CARTA_NOTARIAL_R3,
            P_CARTA_NOTARIAL_O3,
            P_PROTESTO_NOTARIAL_F1,
            P_PROTESTO_NOTARIAL_R1,
            P_PROTESTO_NOTARIAL_O1,
            P_CARTA_PROTESTO_F1,
            P_CARTA_PROTESTO_R1,
            P_CARTA_PROTESTO_O1,
            P_CARTA_PREJECUCION_F1,
            P_CARTA_PREJECUCION_R1,
            P_CARTA_PREJECUCION_O1
        );

    commit;

    OPEN P_RESULTADO FOR
    SELECT 'EXITO' RPTA FROM DUAL;
EXCEPTION WHEN OTHERS THEN
    err_num := SQLCODE;
    err_msg := SQLERRM;

    rollback;

    OPEN P_RESULTADO FOR
    SELECT err_num||' '||err_msg RPTA  FROM DUAL;    

  END SP_CREAR_REQUERIMIENTO;

  PROCEDURE SP_CAMBIA_ESTADO(
    P_REQ_TIPO COB_REQ_CARTAS.REQ_TIPO%TYPE,
	P_REQ_NUMERO COB_REQ_CARTAS.REQ_NUMERO%TYPE,
    P_REQ_ESTADO COB_REQ_CARTAS.REQ_ESTADO%TYPE,
    P_C_USUARIO_MOD COB_REQ_CARTAS.C_USUARIO_MOD%TYPE,    
    P_RESULTADO OUT cursorType) AS

    err_num NUMBER;
    err_msg VARCHAR2(255); 

  BEGIN

    UPDATE COB_REQ_CARTAS 
    SET REQ_ESTADO=P_REQ_ESTADO, 
        C_USUARIO_MOD=P_C_USUARIO_MOD,
        F_USUARIO_MOD=SYSDATE,
        REQ_ENVIO=TRUNC(SYSDATE)     
    WHERE
    REQ_TIPO='RC' AND
	REQ_NUMERO=P_REQ_NUMERO;

    COMMIT;

    OPEN P_RESULTADO FOR
    SELECT 'EXITO' RPTA FROM DUAL;
    EXCEPTION WHEN OTHERS THEN
        err_num := SQLCODE;
        err_msg := SQLERRM;

        rollback;

        OPEN P_RESULTADO FOR
        SELECT err_num||' '||err_msg RPTA  FROM DUAL;   

  END SP_CAMBIA_ESTADO;

  PROCEDURE SP_ELIMINAR_REQUERIMIENTO(
    P_REQ_TIPO COB_REQ_CARTAS.REQ_TIPO%TYPE,
	P_REQ_NUMERO COB_REQ_CARTAS.REQ_NUMERO%TYPE,   
    P_C_USUARIO_MOD COB_REQ_CARTAS.C_USUARIO_MOD%TYPE,    
    P_RESULTADO OUT cursorType) AS

    err_num NUMBER;
    err_msg VARCHAR2(255);   

  BEGIN

    UPDATE COB_REQ_CARTAS 
    SET IS_DELETE='S', 
        C_USUARIO_MOD=P_C_USUARIO_MOD,
        F_USUARIO_MOD=SYSDATE     
    WHERE
    REQ_TIPO='RC' AND
	REQ_NUMERO=P_REQ_NUMERO;

    COMMIT;

    OPEN P_RESULTADO FOR
    SELECT 'EXITO' RPTA FROM DUAL;
    EXCEPTION WHEN OTHERS THEN
        err_num := SQLCODE;
        err_msg := SQLERRM;

        rollback;

        OPEN P_RESULTADO FOR
        SELECT err_num||' '||err_msg RPTA  FROM DUAL;   
  END SP_ELIMINAR_REQUERIMIENTO;

  PROCEDURE SP_LISTAR_CARTAS(
	P_FONDO_ID COB_REQ_CARTAS.FONDO_ID%TYPE,
	P_DVALOR_BV COB_REQ_CARTAS.DVALOR_BV%TYPE,  
    P_RESULTADO OUT cursorType
  ) AS



  BEGIN

     OPEN P_RESULTADO FOR
SELECT * FROM(
          SELECT DISTINCT
            '0001' C_FONDO_ID,
            FO.D_ABREVIADO D_FONDO,
            MC_INV.C_MAE_INVERSION_ID,  
            MI.NINVERSION C_INVERSION_ID,
            MI.DVALOR_BV C_INVERSION,
            MC_PER.C_PERSONA_ID,
            DO2.NDOCUMENTO as A_NRO_DOCUMENTO,
            MP2.TAPATERNO, MP2.TAMATERNO, MP2.TNOMBRES,
            MC.CODFONDO,MC.DVALOR_BV, MC.TIPOCARTA,MC.TIPOFORMATO ,ct.d_descripcion formato,CT1.d_descripcion CARTA,CASE WHEN TRIM(MC.TRECIBIDO)='1' THEN 'RECIBIDO' ELSE
            CASE WHEN TRIM(MC.TRECIBIDO)='2' THEN 'BAJO PUERTA' ELSE 
            CASE WHEN TRIM(MC.TRECIBIDO)='3' THEN 'SIN NOTIFICAR' ELSE ' ' END END END TIPOREC,MC.NOM_ARCHIVO,MC.TRECIBIDO,
        MC.FRECIBIDO,MC.c_usuario_add,mc.femision,mc.sperrecibido,mc.scomentario, REC.REQ_EMISION, REC.TIPO_CARTA, TRE.D_DESCRIPCION REQ_NOMBRE
        FROM SACIF.DOCUMENTO DO JOIN SACIF.PERSONA MP 
            ON DO.CPERSONA = MP.CPERSONA
        INNER JOIN SACIF.PROPIETARIO PRO
            ON PRO.CPERSONA = DO.CPERSONA
        INNER JOIN SACIF.INMUEBLE MINM
            ON MINM.CINMUEBLE = PRO.CINMUEBLE
        INNER JOIN SACIF.ALTERNATIVA_INVERSION AL
            ON AL.CINMUEBLE = MINM.CINMUEBLE
        INNER JOIN SACIF.MAESTRO_INVERSION MI
            ON MI.DVALOR_BV = AL.DVALOR_BV
            AND MI.ITIP_INSTMTO_BURSATIL = '0017'  AND NVL(MOTRASPASO,'0000')<>'0001'
        INNER JOIN SACIF.PERSONA MP2
            ON MP2.CPERSONA = AL.CPERSONA
        INNER JOIN SACIF.DOCUMENTO DO2
            ON DO2.CPERSONA = MP2.CPERSONA
        INNER JOIN MAE_FONDO FO
            on FO.C_FONDO_ID = '0001'
        INNER JOIN MAE_COD_INVERSION MC_INV
            ON MC_INV.C_FONDO_ID = '0001'
            AND MC_INV.C_INVERSION_ID = MI.NINVERSION
        INNER JOIN MAE_COD_PERSONA MC_PER 
            ON MC_PER.C_FONDO_ID = '0001'
            AND MC_PER.C_PERSONA = MP2.CPERSONA  
        INNER JOIN CTDIA.movimiento_cartas MC ON mc.codfondo='0001' and mc.dvalor_bv=al.dvalor_bv 
        INNER JOIN CTDIA.COB_TABLAS CT ON CT.C_TABLA_ID='0008' AND CT.C_TABLA_DET_ID=MC.TIPOFORMATO 
        INNER JOIN CTDIA.COB_TABLAS CT1 ON CT1.C_TABLA_ID='0009' AND CT1.C_TABLA_DET_ID=MC.TIPOCARTA    
        LEFT JOIN COB_REQ_CARTAS REC ON MC.REQ_TIPO=REC.REQ_TIPO AND MC.REQ_NUMERO=REC.REQ_NUMERO
        LEFT JOIN COB_TABLAS TRE ON REC.TIPO_CARTA =TRE.C_TABLA_DET_ID AND TRE.C_TABLA_ID='0622'
        WHERE /* '0001' LIKE P_FONDO_ID||'%'
         AND */TRIM(MI.DVALOR_BV) LIKE TRIM(P_DVALOR_BV)         
         AND MC.DOC_TIPO = 'CN'
         AND MC.DOC_SITUACION <> '9'

        UNION ALL

            SELECT DISTINCT
            '0002' C_FONDO_ID,
            FO.D_ABREVIADO D_FONDO,
            MC_INV.C_MAE_INVERSION_ID,  
            MI.NINVERSION C_INVERSION_ID,
            MI.DVALOR_BV C_INVERSION,    
            MC_PER.C_PERSONA_ID,
            DO2.NDOCUMENTO as A_NRO_DOCUMENTO,
            MP2.TAPATERNO, MP2.TAMATERNO, MP2.TNOMBRES,
             MC.CODFONDO,MC.DVALOR_BV, MC.TIPOCARTA,MC.TIPOFORMATO ,ct.d_descripcion formato,CT1.d_descripcion CARTA,CASE WHEN TRIM(MC.TRECIBIDO)='1' THEN 'RECIBIDO' ELSE
            CASE WHEN TRIM(MC.TRECIBIDO)='2' THEN 'BAJO PUERTA' ELSE 
            CASE WHEN TRIM(MC.TRECIBIDO)='3' THEN 'SIN NOTIFICAR' ELSE ' ' END END END TIPOREC,MC.NOM_ARCHIVO,MC.TRECIBIDO,
        MC.FRECIBIDO,MC.c_usuario_add,mc.femision,mc.sperrecibido,mc.scomentario, REC.REQ_EMISION, REC.TIPO_CARTA, TRE.D_DESCRIPCION REQ_NOMBRE     
        FROM SACIF_POP.DOCUMENTO DO JOIN SACIF_POP.PERSONA MP
            ON DO.CPERSONA = MP.CPERSONA
        INNER JOIN SACIF_POP.PROPIETARIO PRO
            ON PRO.CPERSONA = DO.CPERSONA
        INNER JOIN SACIF_POP.INMUEBLE MINM
            ON MINM.CINMUEBLE = PRO.CINMUEBLE
        INNER JOIN SACIF_POP.ALTERNATIVA_INVERSION AL
            ON AL.CINMUEBLE = MINM.CINMUEBLE
        INNER JOIN SACIF_POP.MAESTRO_INVERSION MI
            ON MI.DVALOR_BV = AL.DVALOR_BV
           AND MI.ITIP_INSTMTO_BURSATIL = '0017'  AND NVL(MOTRASPASO,'0000')<>'0001'
        INNER JOIN SACIF_POP.PERSONA MP2
            ON MP2.CPERSONA = AL.CPERSONA
        INNER JOIN SACIF_POP.DOCUMENTO DO2
            ON DO2.CPERSONA = MP2.CPERSONA
        INNER JOIN MAE_FONDO FO
            on FO.C_FONDO_ID = '0002'
        INNER JOIN MAE_COD_INVERSION MC_INV
            ON MC_INV.C_FONDO_ID = '0002'
            AND MC_INV.C_INVERSION_ID = MI.NINVERSION
    INNER JOIN MAE_COD_PERSONA MC_PER 
            ON MC_PER.C_FONDO_ID = '0002'
            AND MC_PER.C_PERSONA = MP2.CPERSONA 
        INNER JOIN CTDIA.movimiento_cartas MC ON mc.codfondo='0002' and mc.dvalor_bv=al.dvalor_bv 
        INNER JOIN CTDIA.COB_TABLAS CT ON CT.C_TABLA_ID='0008' AND CT.C_TABLA_DET_ID=MC.TIPOFORMATO 
        INNER JOIN CTDIA.COB_TABLAS CT1 ON CT1.C_TABLA_ID='0009' AND CT1.C_TABLA_DET_ID=MC.TIPOCARTA   
        LEFT JOIN COB_REQ_CARTAS REC ON MC.REQ_TIPO=REC.REQ_TIPO AND MC.REQ_NUMERO=REC.REQ_NUMERO      
        LEFT JOIN COB_TABLAS TRE ON REC.TIPO_CARTA =TRE.C_TABLA_DET_ID AND TRE.C_TABLA_ID='0622'        
    WHERE    /*'0002'  LIKE P_FONDO_ID||'%'
         AND */TRIM(MI.DVALOR_BV) LIKE TRIM(P_DVALOR_BV)         
         AND MC.DOC_TIPO = 'CN'
         AND MC.DOC_SITUACION <> '9'
UNION ALL             
            SELECT DISTINCT
            '0003' C_FONDO_ID,
            FO.D_ABREVIADO D_FONDO,
            MC_INV.C_MAE_INVERSION_ID,  
            MI.NINVERSION C_INVERSION_ID,
            MI.DVALOR_BV C_INVERSION,  
            MC_PER.C_PERSONA_ID,
            DO2.NDOCUMENTO as A_NRO_DOCUMENTO,
            MP2.TAPATERNO, MP2.TAMATERNO, MP2.TNOMBRES,
            MC.CODFONDO,MC.DVALOR_BV, MC.TIPOCARTA,MC.TIPOFORMATO ,ct.d_descripcion formato,CT1.d_descripcion CARTA,CASE WHEN TRIM(MC.TRECIBIDO)='1' THEN 'RECIBIDO' ELSE
            CASE WHEN TRIM(MC.TRECIBIDO)='2' THEN 'BAJO PUERTA' ELSE 
            CASE WHEN TRIM(MC.TRECIBIDO)='3' THEN 'SIN NOTIFICAR' ELSE ' ' END END END TIPOREC,MC.NOM_ARCHIVO,MC.TRECIBIDO,
        MC.FRECIBIDO,MC.c_usuario_add,mc.femision,mc.sperrecibido,mc.scomentario, REC.REQ_EMISION, REC.TIPO_CARTA, TRE.D_DESCRIPCION REQ_NOMBRE
        FROM SACIF_MYP.DOCUMENTO DO JOIN SACIF_MYP.PERSONA MP
            ON DO.CPERSONA = MP.CPERSONA
        INNER JOIN SACIF_MYP.PROPIETARIO PRO
            ON PRO.CPERSONA = DO.CPERSONA
        INNER JOIN SACIF_MYP.INMUEBLE MINM
            ON MINM.CINMUEBLE = PRO.CINMUEBLE 
        INNER JOIN SACIF_MYP.ALTERNATIVA_INVERSION AL
            ON AL.CINMUEBLE = MINM.CINMUEBLE
        INNER JOIN SACIF_MYP.MAESTRO_INVERSION MI
            ON MI.DVALOR_BV = AL.DVALOR_BV
            AND MI.ITIP_INSTMTO_BURSATIL = '0017' AND NVL(MOTRASPASO,'0000')<>'0001'
        INNER JOIN SACIF_MYP.PERSONA MP2
            ON MP2.CPERSONA = AL.CPERSONA
        INNER JOIN SACIF_MYP.DOCUMENTO DO2
            ON DO2.CPERSONA = MP2.CPERSONA
        INNER JOIN MAE_FONDO FO
            on FO.C_FONDO_ID = '0003'
        INNER JOIN MAE_COD_INVERSION MC_INV
            ON MC_INV.C_FONDO_ID = '0003'
            AND MC_INV.C_INVERSION_ID = MI.NINVERSION
      INNER JOIN MAE_COD_PERSONA MC_PER 
            ON MC_PER.C_FONDO_ID = '0003'
            AND MC_PER.C_PERSONA = MP2.CPERSONA 
        INNER JOIN CTDIA.movimiento_cartas MC ON mc.codfondo='0003' and mc.dvalor_bv=al.dvalor_bv 
        INNER JOIN CTDIA.COB_TABLAS CT ON CT.C_TABLA_ID='0008' AND CT.C_TABLA_DET_ID=MC.TIPOFORMATO 
        INNER JOIN CTDIA.COB_TABLAS CT1 ON CT1.C_TABLA_ID='0009' AND CT1.C_TABLA_DET_ID=MC.TIPOCARTA   
        LEFT JOIN COB_REQ_CARTAS REC ON MC.REQ_TIPO=REC.REQ_TIPO AND MC.REQ_NUMERO=REC.REQ_NUMERO                
        LEFT JOIN COB_TABLAS TRE ON REC.TIPO_CARTA =TRE.C_TABLA_DET_ID AND TRE.C_TABLA_ID='0622'                
    WHERE  /*'0003'  LIKE P_FONDO_ID||'%'
         AND */TRIM(MI.DVALOR_BV) LIKE TRIM(P_DVALOR_BV)         
         AND MC.DOC_TIPO = 'CN'
         AND MC.DOC_SITUACION <> '9'
  UNION ALL             
            SELECT DISTINCT
            '0004' C_FONDO_ID,
            FO.D_ABREVIADO D_FONDO,
            MC_INV.C_MAE_INVERSION_ID,  
            MI.NINVERSION C_INVERSION_ID,
            MI.DVALOR_BV C_INVERSION,    
            MC_PER.C_PERSONA_ID,
            DO2.NDOCUMENTO as A_NRO_DOCUMENTO,
            MP2.TAPATERNO, MP2.TAMATERNO, MP2.TNOMBRES,
            MC.CODFONDO,MC.DVALOR_BV, MC.TIPOCARTA,MC.TIPOFORMATO ,ct.d_descripcion formato,CT1.d_descripcion CARTA,CASE WHEN TRIM(MC.TRECIBIDO)='1' THEN 'RECIBIDO' ELSE
            CASE WHEN TRIM(MC.TRECIBIDO)='2' THEN 'BAJO PUERTA' ELSE 
            CASE WHEN TRIM(MC.TRECIBIDO)='3' THEN 'SIN NOTIFICAR' ELSE ' ' END END END TIPOREC,MC.NOM_ARCHIVO,MC.TRECIBIDO,
        MC.FRECIBIDO,MC.c_usuario_add,mc.femision,mc.sperrecibido,mc.scomentario, REC.REQ_EMISION, REC.TIPO_CARTA, TRE.D_DESCRIPCION REQ_NOMBRE
        FROM SACIF_PRH.DOCUMENTO DO JOIN SACIF_PRH.PERSONA MP 
            ON DO.CPERSONA = MP.CPERSONA
        INNER JOIN SACIF_PRH.PROPIETARIO PRO
            ON PRO.CPERSONA = DO.CPERSONA
        INNER JOIN SACIF_PRH.INMUEBLE MINM
            ON MINM.CINMUEBLE = PRO.CINMUEBLE
        INNER JOIN SACIF_PRH.ALTERNATIVA_INVERSION AL
            ON AL.CINMUEBLE = MINM.CINMUEBLE
        INNER JOIN SACIF_PRH.MAESTRO_INVERSION MI
            ON MI.DVALOR_BV = AL.DVALOR_BV
             AND MI.ITIP_INSTMTO_BURSATIL = '0017' AND NVL(MOTRASPASO,'0000')<>'0001'
        INNER JOIN SACIF_PRH.PERSONA MP2
            ON MP2.CPERSONA = AL.CPERSONA
        INNER JOIN SACIF_PRH.DOCUMENTO DO2
            ON DO2.CPERSONA = MP2.CPERSONA
        INNER JOIN MAE_FONDO FO
            ON FO.C_FONDO_ID = '0004'
        INNER JOIN MAE_COD_INVERSION MC_INV
            ON MC_INV.C_FONDO_ID = '0004'
            AND MC_INV.C_INVERSION_ID = MI.NINVERSION
         INNER JOIN EVA.MAE_COD_PERSONA MC_PER 
            ON MC_PER.C_FONDO_ID = '0004'
            AND MC_PER.C_PERSONA = MP2.CPERSONA
        INNER JOIN CTDIA.movimiento_cartas MC ON mc.codfondo='0004' and mc.dvalor_bv=al.dvalor_bv 
        INNER JOIN CTDIA.COB_TABLAS CT ON CT.C_TABLA_ID='0008' AND CT.C_TABLA_DET_ID=MC.TIPOFORMATO 
        INNER JOIN CTDIA.COB_TABLAS CT1 ON CT1.C_TABLA_ID='0009' AND CT1.C_TABLA_DET_ID=MC.TIPOCARTA  
        LEFT JOIN COB_REQ_CARTAS REC ON MC.REQ_TIPO=REC.REQ_TIPO AND MC.REQ_NUMERO=REC.REQ_NUMERO  
        LEFT JOIN COB_TABLAS TRE ON REC.TIPO_CARTA =TRE.C_TABLA_DET_ID AND TRE.C_TABLA_ID='0622'                
    WHERE /*'0004' LIKE P_FONDO_ID||'%'
         AND */TRIM(MI.DVALOR_BV) LIKE TRIM(P_DVALOR_BV)         
         AND MC.DOC_TIPO = 'CN'
         AND MC.DOC_SITUACION <> '9'

         UNION ALL
         --PROTESTOS POR FONDO
          SELECT DISTINCT
            '0001' C_FONDO_ID,
            FO.D_ABREVIADO D_FONDO,
            MC_INV.C_MAE_INVERSION_ID,  
            MI.NINVERSION C_INVERSION_ID,
            MI.DVALOR_BV C_INVERSION,
            MC_PER.C_PERSONA_ID,
            DO2.NDOCUMENTO as A_NRO_DOCUMENTO,
            MP2.TAPATERNO, MP2.TAMATERNO, MP2.TNOMBRES,
            MC.CODFONDO,MC.DVALOR_BV, '0005' TIPOCARTA, NULL TIPOFORMATO ,NULL formato,'PROTESTO TCHN' CARTA,
            null TIPOREC,null NOM_ARCHIVO, null TRECIBIDO,
        MC.FPROTESTO FRECIBIDO,MC.c_usuario_add,mc.femision,null sperrecibido,MC.COMENTARIO scomentario, 
        REC.REQ_EMISION, REC.TIPO_CARTA, TRE.D_DESCRIPCION REQ_NOMBRE
        FROM SACIF.DOCUMENTO DO 
        INNER JOIN SACIF.PERSONA MP ON DO.CPERSONA = MP.CPERSONA
        INNER JOIN SACIF.PROPIETARIO PRO ON PRO.CPERSONA = DO.CPERSONA
        INNER JOIN SACIF.INMUEBLE MINM ON MINM.CINMUEBLE = PRO.CINMUEBLE
        INNER JOIN SACIF.ALTERNATIVA_INVERSION AL ON AL.CINMUEBLE = MINM.CINMUEBLE
        INNER JOIN SACIF.MAESTRO_INVERSION MI ON MI.DVALOR_BV = AL.DVALOR_BV /*AND MI.ITIP_INSTMTO_BURSATIL = '0017'  AND NVL(MOTRASPASO,'0000')<>'0001'*/
        INNER JOIN SACIF.PERSONA MP2 ON MP2.CPERSONA = AL.CPERSONA
        INNER JOIN SACIF.DOCUMENTO DO2 ON DO2.CPERSONA = MP2.CPERSONA
        INNER JOIN MAE_FONDO FO ON FO.C_FONDO_ID = '0001'
        INNER JOIN MAE_COD_INVERSION MC_INV ON MC_INV.C_FONDO_ID = '0001' AND MC_INV.C_INVERSION_ID = MI.NINVERSION
        INNER JOIN MAE_COD_PERSONA MC_PER ON MC_PER.C_FONDO_ID = '0001' AND MC_PER.C_PERSONA = MP2.CPERSONA  
        INNER JOIN CTDIA.MOVIMIENTO_PROTESTO MC ON mc.codfondo='0001' and TRIM(mc.dvalor_bv)=TRIM(al.dvalor_bv)           
        LEFT JOIN COB_REQ_CARTAS REC ON MC.REQ_TIPO=REC.REQ_TIPO AND MC.REQ_NUMERO=REC.REQ_NUMERO
        LEFT JOIN COB_TABLAS TRE ON REC.TIPO_CARTA =TRE.C_TABLA_DET_ID AND TRE.C_TABLA_ID='0622'
    WHERE  /*'0001' LIKE P_FONDO_ID ||'%'
         AND */TRIM(MI.DVALOR_BV) LIKE TRIM(P_DVALOR_BV)         
         AND MC.DOC_TIPO = 'PN'
         AND MC.IS_DELETE = 'N'

         UNION ALL

        SELECT DISTINCT
            '0002' C_FONDO_ID,
            FO.D_ABREVIADO D_FONDO,
            MC_INV.C_MAE_INVERSION_ID,  
            MI.NINVERSION C_INVERSION_ID,
            MI.DVALOR_BV C_INVERSION,
            MC_PER.C_PERSONA_ID,
            DO2.NDOCUMENTO as A_NRO_DOCUMENTO,
            MP2.TAPATERNO, MP2.TAMATERNO, MP2.TNOMBRES,
            MC.CODFONDO,MC.DVALOR_BV, '0005' TIPOCARTA, NULL TIPOFORMATO ,NULL formato,'PROTESTO TCHN' CARTA,
            null TIPOREC,null NOM_ARCHIVO, null TRECIBIDO,
            MC.FPROTESTO FRECIBIDO,MC.c_usuario_add,mc.femision,null sperrecibido,MC.COMENTARIO scomentario, 
            REC.REQ_EMISION, REC.TIPO_CARTA, TRE.D_DESCRIPCION REQ_NOMBRE
        FROM SACIF_POP.DOCUMENTO DO 
        INNER JOIN SACIF_POP.PERSONA MP ON DO.CPERSONA = MP.CPERSONA
        INNER JOIN SACIF_POP.PROPIETARIO PRO ON PRO.CPERSONA = DO.CPERSONA
        INNER JOIN SACIF_POP.INMUEBLE MINM ON MINM.CINMUEBLE = PRO.CINMUEBLE
        INNER JOIN SACIF_POP.ALTERNATIVA_INVERSION AL ON AL.CINMUEBLE = MINM.CINMUEBLE
        INNER JOIN SACIF_POP.MAESTRO_INVERSION MI ON MI.DVALOR_BV = AL.DVALOR_BV /*AND MI.ITIP_INSTMTO_BURSATIL = '0017'  AND NVL(MOTRASPASO,'0000')<>'0001'*/
        INNER JOIN SACIF_POP.PERSONA MP2 ON MP2.CPERSONA = AL.CPERSONA
        INNER JOIN SACIF_POP.DOCUMENTO DO2 ON DO2.CPERSONA = MP2.CPERSONA
        INNER JOIN MAE_FONDO FO ON FO.C_FONDO_ID = '0002'
        INNER JOIN MAE_COD_INVERSION MC_INV ON MC_INV.C_FONDO_ID = '0002' AND MC_INV.C_INVERSION_ID = MI.NINVERSION
        INNER JOIN MAE_COD_PERSONA MC_PER ON MC_PER.C_FONDO_ID = '0002' AND MC_PER.C_PERSONA = MP2.CPERSONA  
        INNER JOIN CTDIA.MOVIMIENTO_PROTESTO MC ON mc.codfondo='0002' and TRIM(mc.dvalor_bv)=TRIM(al.dvalor_bv)           
        LEFT JOIN COB_REQ_CARTAS REC ON MC.REQ_TIPO=REC.REQ_TIPO AND MC.REQ_NUMERO=REC.REQ_NUMERO
        LEFT JOIN COB_TABLAS TRE ON REC.TIPO_CARTA =TRE.C_TABLA_DET_ID AND TRE.C_TABLA_ID='0622'
    WHERE  /*'0002' LIKE P_FONDO_ID ||'%'
         AND */TRIM(MI.DVALOR_BV) LIKE TRIM(P_DVALOR_BV)         
         AND MC.DOC_TIPO = 'PN'
         AND MC.IS_DELETE = 'N'    

         UNION ALL

        SELECT DISTINCT
            '0003' C_FONDO_ID,
            FO.D_ABREVIADO D_FONDO,
            MC_INV.C_MAE_INVERSION_ID,  
            MI.NINVERSION C_INVERSION_ID,
            MI.DVALOR_BV C_INVERSION,
            MC_PER.C_PERSONA_ID,
            DO2.NDOCUMENTO as A_NRO_DOCUMENTO,
            MP2.TAPATERNO, MP2.TAMATERNO, MP2.TNOMBRES,
            MC.CODFONDO,MC.DVALOR_BV, '0005' TIPOCARTA, NULL TIPOFORMATO ,NULL formato,'PROTESTO TCHN' CARTA,
            null TIPOREC,null NOM_ARCHIVO, null TRECIBIDO,
            MC.FPROTESTO FRECIBIDO,MC.c_usuario_add,mc.femision,null sperrecibido,MC.COMENTARIO scomentario, 
            REC.REQ_EMISION, REC.TIPO_CARTA, TRE.D_DESCRIPCION REQ_NOMBRE
        FROM SACIF_POP.DOCUMENTO DO 
        INNER JOIN SACIF_MYP.PERSONA MP ON DO.CPERSONA = MP.CPERSONA
        INNER JOIN SACIF_MYP.PROPIETARIO PRO ON PRO.CPERSONA = DO.CPERSONA
        INNER JOIN SACIF_MYP.INMUEBLE MINM ON MINM.CINMUEBLE = PRO.CINMUEBLE
        INNER JOIN SACIF_MYP.ALTERNATIVA_INVERSION AL ON AL.CINMUEBLE = MINM.CINMUEBLE
        INNER JOIN SACIF_MYP.MAESTRO_INVERSION MI ON MI.DVALOR_BV = AL.DVALOR_BV /*AND MI.ITIP_INSTMTO_BURSATIL = '0017'  AND NVL(MOTRASPASO,'0000')<>'0001'*/
        INNER JOIN SACIF_MYP.PERSONA MP2 ON MP2.CPERSONA = AL.CPERSONA
        INNER JOIN SACIF_MYP.DOCUMENTO DO2 ON DO2.CPERSONA = MP2.CPERSONA
        INNER JOIN MAE_FONDO FO ON FO.C_FONDO_ID = '0003'
        INNER JOIN MAE_COD_INVERSION MC_INV ON MC_INV.C_FONDO_ID = '0003' AND MC_INV.C_INVERSION_ID = MI.NINVERSION
        INNER JOIN MAE_COD_PERSONA MC_PER ON MC_PER.C_FONDO_ID = '0003' AND MC_PER.C_PERSONA = MP2.CPERSONA  
        INNER JOIN CTDIA.MOVIMIENTO_PROTESTO MC ON mc.codfondo='0003' and TRIM(mc.dvalor_bv)=TRIM(al.dvalor_bv)           
        LEFT JOIN COB_REQ_CARTAS REC ON MC.REQ_TIPO=REC.REQ_TIPO AND MC.REQ_NUMERO=REC.REQ_NUMERO
        LEFT JOIN COB_TABLAS TRE ON REC.TIPO_CARTA =TRE.C_TABLA_DET_ID AND TRE.C_TABLA_ID='0622'
    WHERE  /*'0003' LIKE P_FONDO_ID ||'%'
         AND */TRIM(MI.DVALOR_BV) LIKE TRIM(P_DVALOR_BV)         
         AND MC.DOC_TIPO = 'PN'
         AND MC.IS_DELETE = 'N'            
)
        order by femision desc;     

  END SP_LISTAR_CARTAS;

END PKG_REQUERIMIENTOS;

/
